# Generated by Django 4.0.5 on 2022-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=40)),
                ('userid', models.CharField(max_length=40)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='favmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=40)),
                ('userid', models.CharField(max_length=40)),
                ('isfav', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Popularmodel',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('stars', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=40)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updatedat', '-createdat'],
            },
        ),
        migrations.CreateModel(
            name='Recommendedmodel',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('stars', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=40)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updatedat', '-createdat'],
            },
        ),
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('userid', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
